EPOCHS: 400
EVAL_CROP_SIZE: (1025, 2049)
TRAIN_CROP_SIZE: 769
BATCH_SIZE: 4
TEST_BATCH_SIZE: 4
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
DATASET: "cityscape"

MODEL:
    MODEL_NAME: "deeplabv3_plus"
    BACKBONE: "resnet101"

TEST:
    TEST_MODEL_PATH: ../trained_models/deeplabv3_plus_resnet101_segmentron.pth

SOLVER:
    LR: 0.02
