DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 240
    BATCH_SIZE: 4
    CROP_SIZE: 768
    BACKBONE_PRETRAINED: False
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (1024, 2048)
#    TEST_MODEL_PATH: ../trained_models/icnet_plus_resnet101_segmentron.pth

SOLVER:
    LR: 0.01

MODEL:
    MODEL_NAME: "icnet"
    BACKBONE: "resnet50"
    OUTPUT_STRIDE: 8
    BACKBONE_SCALE: 0.5
